### ISSUE TITLE
Support for hierarchical topics

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/mqtt-gateway#23] opened 2017-02-23 18:01 UTC
With the recent merge of https://github.com/EnMasseProject/artemis-image/pull/16/files , the broker is now configured to support hierarchical topics with MQTT semantics, and this works with AMQP clients. 

For MQTT, this does not work when I create subscriber and publisher as follows:

mosquitto_sub -h 172.30.186.198 -p 1883 -q 1 -t "mytopic/#"
mosquitto_pub -h 172.30.186.198 -p 1883 -q 1 -t mytopic/foo/bar -m hei

I get the following in the gateway log:

18:00:34.685 [vert.x-eventloop-thread-0] ERROR enmasse.mqtt.AmqpBridge - Published message : MQTT client mosqsub/16490-strappi is not subscribed to mytopic/foo/bar !!

The whole log:

18:00:30.175 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttGateway - CONNECT from MQTT client mosqsub/16490-strappi
18:00:30.186 [vert.x-eventloop-thread-0] INFO  e.m.e.AmqpSubscriptionServiceEndpoint - AMQP close delivery Accepted{}
18:00:30.187 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - CONNACK to MQTT client mosqsub/16490-strappi [accepted]
18:00:30.188 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttGateway - Opened AMQP bridge for client mosqsub/16490-strappi
18:00:30.189 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - SUBSCRIBE [1] from MQTT client mosqsub/16490-strappi
18:00:30.247 [vert.x-eventloop-thread-0] INFO  e.m.e.AmqpSubscriptionServiceEndpoint - AMQP subscribe delivery Accepted{}
18:00:30.248 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - SUBACK [1] to MQTT client mosqsub/16490-strappi
18:00:34.662 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttGateway - CONNECT from MQTT client mosqpub/16517-strappi
18:00:34.669 [vert.x-eventloop-thread-0] INFO  e.m.e.AmqpSubscriptionServiceEndpoint - AMQP close delivery Accepted{}
18:00:34.669 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - CONNACK to MQTT client mosqpub/16517-strappi [accepted]
18:00:34.670 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttGateway - Opened AMQP bridge for client mosqpub/16517-strappi
18:00:34.670 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - PUBLISH [1] from MQTT client mosqpub/16517-strappi
18:00:34.682 [vert.x-eventloop-thread-0] INFO  e.mqtt.endpoints.AmqpPublishEndpoint - AMQP publish delivery Accepted{}
18:00:34.683 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - PUBACK [1] to MQTT client mosqpub/16517-strappi
18:00:34.684 [vert.x-eventloop-thread-0] INFO  e.m.endpoints.AmqpReceiverEndpoint - Received Message{header=Header{durable=true, priority=null, ttl=null, firstAcquirer=null, deliveryCount=0}properties=Properties{messageId=1, userId=null, to='mytopic/foo/bar', subject='null', replyTo='null', correlationId=null, contentType=null, contentEncoding=null, absoluteExpiryTime=null, creationTime=null, groupId='null', groupSequence=null, replyToGroupId='null'}message_annotations=MessageAnnotations{{x-opt-retain-message=false, x-opt-mqtt-qos=1}}body=Data{hei}}
18:00:34.685 [vert.x-eventloop-thread-0] ERROR enmasse.mqtt.AmqpBridge - Published message : MQTT client mosqsub/16490-strappi is not subscribed to mytopic/foo/bar !!
18:00:34.685 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - DISCONNECT from MQTT client mosqpub/16517-strappi
18:00:34.685 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - Close from MQTT client mosqpub/16517-strappi
18:00:34.686 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.MqttGateway - Closed AMQP bridge for client mosqpub/16517-strappi
18:00:34.688 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - AMQP connection closed with Router.qdrouterd-2636875659-0yg7r
18:00:34.689 [vert.x-eventloop-thread-0] WARN  enmasse.mqtt.AmqpBridge - MQTT endpoint for client mosqpub/16517-strappi already closed
18:00:34.689 [vert.x-eventloop-thread-0] INFO  enmasse.mqtt.AmqpBridge - AMQP disconnection with Router.qdrouterd-2636875659-0yg7r
18:00:34.689 [vert.x-eventloop-thread-0] WARN  enmasse.mqtt.AmqpBridge - MQTT endpoint for client mosqpub/16517-strappi already closed

**Comment by grs** [comment] 2017-02-23 18:26
Hierarchical topics were already supported *before* that change, and wildcards worked not only direct against the broker but through the router *and* in conjunction with the subscription control service over AMQP.

The issue previously was that the separator and wildcard symbols recognised by the broker did not match those defined by MQTT.

**Comment by lulf** [comment] 2017-02-24 07:51
I realize that the subserv log would also be useful. Here is the logs for gateway and subserv for a different test run:

http://people.redhat.com/~ulilleen/mqtt_wildcard_gateway.log
http://people.redhat.com/~ulilleen/mqtt_wildcard_subserv.log

**Comment by ppatierno** [comment] 2017-02-24 09:39
I got the problem due to a security check I made before delivering message : mytopic/# doesn't match with mytopic/foo/bar ... a more complex match expression is needed.
Btw I can't reproduce it now, because if I try to subscribe I see following error in subserv : 

received message: {"message_id":1,"subject":"subscribe","correlation_id":"$mqtt.to.mosqsub/26224-localhost.publish","body":{"mytopyc/#":"1"}}
subscribe($mqtt.to.mosqsub/26224-localhost.publish,[object Object])
subscribe($mqtt.to.mosqsub/26224-localhost.publish,[object Object]) failed: Error: Unrecognised topic: mytopyc/#

with current log in my MQTT gateway : 

AMQP subscribe delivery Rejected{error=Error{condition=amqp:precondition-failed, description='Error: Unrecognised topic: mytopyc/#', info=null}}

**Comment by ppatierno** [comment] 2017-02-24 09:42
Sorry guys my fault !!! mytopyc ... instead of mytopic !!!

**Comment by ppatierno** [comment] 2017-02-24 13:55
@lulf @grs I fixed this but ... 

The Ulf case works fine.

I can't have it working the case where subscriber subscribes to mytopic/+/bar and publisher publishes on mytopic/foo/bar. The MQTT gateway doesn't receive any message to publish in this case.
I see that the subserv is accepting the subscription.

**Comment by ppatierno** [comment] 2017-02-24 13:58
I have just tried the AMQP way with following example : 

python simple_recv.py -a amqp://172.30.91.85/mytopic/+/bar -m 1

and

python simple_send.py -a amqp://172.30.91.85/mytopic/foo/bar -m 1

but the receiver doesn't get the message.

**Comment by lulf** [comment] 2017-02-24 14:15
This works for me when using qpid-cpp, but not the python example. 

qpid-receive -a 'mytopic/+/bar; {node:{type:topic}}' --ack-frequency 1 -f -b 172.17.0.9:5672
qpid-send -a 'mytopic/foo/bar; {node:{type:topic}}' -b 172.17.0.9:5672 --content-stdin

**Comment by grs** [comment] 2017-02-24 14:18
In the qpid::messaging api, the address is of the form node/subject, so you catully need more quoates around that in order to have the whole address considered as the source/target: 

qpid-receive -a '"mytopic/+/bar"; {node:{type:topic}}' --ack-frequency 1 -f -b 172.17.0.9:5672
qpid-send -a '"mytopic/foo/bar"; {node:{type:topic}}' -b 172.17.0.9:5672 --content-stdin

My guess is that won't work either.

**Comment by lulf** [comment] 2017-02-24 14:24
[lulf@strappi openshift-configuration]$ PN_TRACE_FRM=1 qpid-receive -a '"mytopic/+/bar"; {node:{type:topic}}' --ack-frequency 1 -f -b 172.17.0.9:5673
[0x564523836420]:  -> AMQP
[0x564523836420]:  <- AMQP
[0x564523836420]:0 -> @open(16) [container-id="596b6eae-c427-4f7d-a96e-7cb49b0132e4", channel-max=32767, properties={:"qpid.client_process"=:"qpid-receive", :"qpid.client_pid"=22781, :"qpid.client_ppid"=8541}]
[0x564523836420]:0 <- @open(16) [container-id="mytopic-843386344-8wni7", max-frame-size=4294967295, channel-max=65535, idle-time-out=30000, offered-capabilities=@PN_SYMBOL[:"sole-connection-for-container", :"DELAYED_DELIVERY", :"SHARED-SUBS", :"NODE_SERVER", :"ANONYMOUS-RELAY"], properties={:product="apache-activemq-artemis", :version="2.0.0-SNAPSHOT"}]
[0x564523836420]:0 -> @begin(17) [next-outgoing-id=0, incoming-window=2147483647, outgoing-window=2147483647]
[0x564523836420]:0 <- @begin(17) [remote-channel=0, next-outgoing-id=1, incoming-window=2147483647, outgoing-window=2147483647, handle-max=65535]
[0x564523836420]:0 -> @attach(18) [name="mytopic/+/bar_7ad9f26a-03ec-4c89-a4b5-234c6698c495", handle=0, role=true, snd-settle-mode=2, rcv-settle-mode=0, source=@source(40) [address="mytopic/+/bar", durable=0, timeout=0, dynamic=false, capabilities=:topic], target=@target(41) [address="mytopic/+/bar", durable=0, timeout=0, dynamic=false], initial-delivery-count=0]
[0x564523836420]:0 <- @attach(18) [name="mytopic/+/bar_7ad9f26a-03ec-4c89-a4b5-234c6698c495", handle=0, role=false, snd-settle-mode=2, rcv-settle-mode=0, target=@target(41) [address="mytopic/+/bar"], incomplete-unsettled=false, initial-delivery-count=0]
[0x564523836420]:0 <- @detach(22) [handle=0, closed=true, error=@error(29) [condition=:"amqp:illegal-state", description="Address mytopic/+/bar is not configured for topic support"]]
qpid-receive: Link detached by peer with amqp:illegal-state: Address mytopic/+/bar is not configured for topic support
[0x564523836420]:0 -> @detach(22) [handle=0, closed=true]

**Comment by ppatierno** [comment] 2017-02-24 14:36
Using the more quotes as @grs said on an example with mytopic/# works.

qpid-receive -a '"mytopic/#"; {node:{type:topic}}' --ack-frequency 1 -f -b 172.30.91.85:5672
pid-send -a '"mytopic/foo/bar"; {node:{type:topic}}' -b 172.30.91.85:5672 --content-stdin

**Comment by grs** [comment] 2017-02-24 14:36
does bar/+ work?

**Comment by ppatierno** [comment] 2017-02-24 14:37
I have tried this : 

qpid-receive -a '"mytopic/bar/+"; {node:{type:topic}}' --ack-frequency 1 -f -b 172.30.91.85:5672
qpid-send -a '"mytopic/bar/test"; {node:{type:topic}}' -b 172.30.91.85:5672 --content-stdin

but it doesn't work.

**Comment by grs** [comment] 2017-02-24 14:38
but, to clarify, receiving on my/topic/bar/#  and sending to mytopic/bar/test does?

**Comment by ppatierno** [comment] 2017-02-24 14:39
Yes ! :-) Just tried against the broker

**Comment by grs** [comment] 2017-02-24 14:41
Does it also work through the router?

**Comment by grs** [comment] 2017-02-24 14:42
Or better, does mytopic/bar/+ work against the broker directly? If not that is presumably a broker issue  we can log.

**Comment by ppatierno** [comment] 2017-02-24 14:44
Summary ....

sub ->  mytopic/bar/#
pub -> mytopic/bar/test

works against broker or through the router

sub ->  mytopic/bar/+
pub -> mytopic/bar/test

doesn't work in both cases.

**Comment by ppatierno** [comment] 2017-02-24 16:39
I have just opened this JIRA for Artemis : 
https://issues.apache.org/jira/browse/ARTEMIS-997

**Comment by ppatierno** [comment] 2017-03-01 09:09
I'm going to close it because it should be fixed on the MQTT gateway side on behalf of 156d715b2f59fe0456018fe1345562fac986322b

Waiting for news on the Artemis JIRA.

**Closed by ppatierno** 2017-03-01 09:09 UTC
